name: Lint All

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install zhlint
        run: yarn global add zhlint

      - name: Lint All Markdown Files
        run: |
          mkdir -p linted_output
          linted_failed=0
          find . -type f -name '*.md' | while read file; do
            output_dir="linted_output/$(dirname "$file")"
            mkdir -p "$output_dir"
            set +e
            zhlint "$file" > /dev/null 2>&1
            if [ $? -ne 0 ]; then
              linted_failed=1
              zhlint "$file" --output="$output_dir/$(basename "$file")"
            fi
            set -e
          done
          echo "linted_failed=$linted_failed" >> "$GITHUB_ENV"

      - name: Upload Linted Markdown
        uses: actions/upload-artifact@v4
        with:
          name: linted-markdown
          path: linted_output/

      - name: Check lint errors
        run: |
          set -e
          if [ "$linted_failed" -ne 0 ]; then
            echo "Linting errors found. Please check the uploaded artifacts and the lint logs."
            exit 1
          fi
